### ISSUE TITLE
Suggestion: update remote HEAD as well

### ISSUE THREAD

**Issue by lafiosca** [agocs/mastertomain#1]
After deleting the master branch, I'm left with a dangling remote HEAD reference in my local git repository which was cloned before the change:

```
$ git branch -r
warning: ignoring broken ref refs/remotes/origin/HEAD
  origin/main
```

This can be fixed by (1) updating it to the new branch:
```
$ git remote set-head origin main
```

Or by (2) removing it entirely:
```
$ git remote set-head origin -d
```

After updating it (1), the output looks like this:
```
$ git branch -r
  origin/HEAD -> origin/main
  origin/main
```

Credit due to this response: https://stackoverflow.com/a/6838756/8972418

**Comment by agocs** [comment]
Awesome, thanks. I obviously didn't spend a whole ton of time testing this. I'll update the script.

**Comment by agocs** [comment]
Done! I used this opportunity to make the cleanup steps more automated as well.
